# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- weibo
- category
- tag
#- tagcloud
- archive
- recent_posts
- links

# Links
links:
    潮鸣: http://yunhuanran.github.io

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: aidaiz

# Baidu share
baidushare: true

